### PR TITLE
Miniforge docker image and publish images to ghcr.io

### PR DESCRIPTION
**Pull request by banesullivan**
Hopefully, this makes it easier to run RGD within docker (or natively) on an M1 Mac - cc @mcovalt 

At the moment, this will not work with the tox testing environment.

To test:

```bash
docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.override.miniforge.yml build
docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.override.miniforge.yml up
```

Current image sizes:

```
REPOSITORY                          TAG          IMAGE ID       CREATED        SIZE
django                              latest       4fc25bb20b1b   11 seconds ago   1.37GB
celery                              latest       3f82a97a1242   2 minutes ago    2.93GB
miniforge                           latest       0dc419cbbdaf   2 days ago       4.94GB
```

Once we get to #674, we should try to trim these down and ship a "base image" for downstream RGD projects - having all of the dependencies installed (but not any RGD subpackages)

### CODE REVIEW

**Comment by banesullivan** [comment]
I have also added a GitHub Action here to build and publish each of the three Docker images (for development use only) to the GitHub container registry. These can in many cases rapidly speed up development if you override the `django` and `celery` services to pull the images directly from ghcr.io (I have added a docker-compose override in `docker-compose.override.no-build.yml`).

These can be used by:

```py
docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.override.no-build.yml build
docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.override.no-build.yml up
```

(I think)

**Comment by banesullivan** [comment]
NOTE: the miniforge image does not currently support/implement FUSE. We can add this, but I chose not to initially

**Comment by banesullivan** [comment]
After this, we can address #674

**Comment by mcovalt** [comment]
This is awesome! Looking forward to testing it out!

**Comment by banesullivan** [comment]
Merging. Dependency refinement and image optimization can come later

**Pull request merged**
