### PR TITLE
STAC Browser

### PR DESCRIPTION
**Pull request by mcovalt**
This imports version 2.0.0 of the [STAC Browser](https://github.com/radiantearth/stac-browser). The build process was difficult to automate (a couple patches), so I made the decision to build and commit the result into the tree. STAC Browser 3.0.0 is the next release, so we can automate the build process there.

The existing STAC-API was fleshed out a bit more to handle the browser.

The STAC Browser is visible at `/rgd_imagery/stac_browser/`.

Here is an example browsing the user's "default" collection:

Capture

### CODE REVIEW

**Comment by mcovalt** [comment]
I want to link two threads that have been discussed elsewhere and fixed here:

- https://github.com/ResonantGeoData/ResonantGeoData/pull/506#discussion_r703728047
- https://github.com/ResonantGeoData/ResonantGeoData/pull/506#discussion_r703729173

**Comment by aashish24** [comment]
Very cool @mcovalt can you post a image with landsat collection, possible?

**Comment by mcovalt** [comment]
@aashish24 I bet I can. I'm downloading the collection now.

**Comment by mcovalt** [comment]
@aashish24 See attached for an item detail of a Landsat collection

ls_item_detail

**Comment by mcovalt** [comment]
@banesullivan I've fixed up the merge conflicts.

**Review by banesullivan — CHANGES_REQUESTED** [review]
This is looking really, really great! Thanks for all the effort here, @mcovalt!

The updates to the serializers and reorganization are very much needed on their own.

Considering that STAC Browser does not currently support pagination, and trying to load large amounts of data will timeout, let's set a max query count limit to fail loading the stac browser. Let's make this a setting called `RGD_STAC_BROWSER_LIMIT` with a default value of `1000` for now. If the raster query count exceeds that, just raise a server error (perhaps make sure this error is sent back in the response too).

**Comment by mcovalt** [comment]
Thanks for the feedback, @banesullivan. I've implemented, documented, and tested the `RGD_STAC_BROWSER_LIMIT` setting in bfaa4654fa232c957067f8ec833bab7109ab1158.

**Comment by banesullivan** [comment]
Awesome, thanks!!

----

The error happening is unrelated to these changes AFAIK so we are good to merge.

We're seeing this error with `gdal.Warp` where the arguments are incorrectly passed:

```py
../../.tox/test-rgd-imagery/lib/python3.8/site-packages/large_image_source_gdal/__init__.py:1137: in getRegion
    gdal.Warp(outputPath, ds, options=gdalParams)
        __class__  = <class 'large_image_source_gdal.GDALFileTileSource'>
        br         = (334.0, 628.0)
        ds         = <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f28b9356630> >
        fd         = 23
        format     = ('image',)
        gdalParams = ['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...]
        iterInfo   = {'encoding': 'TILED', 'format': ('numpy',), 'frame': None, 'level': 2, ...}
        kwargs     = {'encoding': 'TILED', 'region': {'bottom': 627.64, 'left': 19.23, 'right': 333.73, 'top': 383.18, ...}}
        outHeight  = 245
        outWidth   = 315
        outputPath = '/tmp/tiledGeoRegion_uptqomyj.tiff'
        self       = <large_image_source_gdal.GDALFileTileSource object at 0x7f28b937a8b0>
        srs        = None
        tl         = (19.0, 383.0)
        useGDALWarp = True
../../.tox/test-rgd-imagery/lib/python3.8/site-packages/osgeo/gdal.py:673: in Warp
    (opts, callback, callback_data) = WarpOptions(**kwargs)
        destNameOrDestDS = '/tmp/tiledGeoRegion_uptqomyj.tiff'
        kwargs     = {'options': ['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...]}
        srcDSOrSrcDSTab = <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f28b9356630> >
../../.tox/test-rgd-imagery/lib/python3.8/site-packages/osgeo/gdal.py:660: in WarpOptions
    return (GDALWarpAppOptions(new_options), callback, callback_data)
        callback   = None
        callback_data = None
        coordinateOperation = None
        copyMetadata = True
        creationOptions = None
        cropToCutline = False
        cutlineBlend = None
        cutlineDSName = None
        cutlineLayer = None
        cutlineSQL = None
        cutlineWhere = None
        dstAlpha   = False
        dstNodata  = None
        dstSRS     = None
        errorThreshold = None
        format     = None
        geoloc     = False
        height     = 0
        metadataConflictValue = None
        multithread = False
        new_options = ['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...]
        options    = ['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...]
        outputBounds = None
        outputBoundsSRS = None
        outputType = 0
        overviewLevel = 'AUTO'
        polynomialOrder = None
        resampleAlg = None
        rpc        = False
        setColorInterpretation = False
        srcAlpha   = False
        srcNodata  = None
        srcSRS     = None
        targetAlignedPixels = False
        tps        = False
        transformerOptions = None
        warpMemoryLimit = None
        warpOptions = None
        width      = 0
        workingType = 0
        xRes       = None
        yRes       = None
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <osgeo.gdal.GDALWarpAppOptions;  >
args = (['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...],)

    def __init__(self, *args):
        """__init__(GDALWarpAppOptions self, char ** options) -> GDALWarpAppOptions"""
>       this = _gdal.new_GDALWarpAppOptions(*args)
E       TypeError: sequence must contain strings

args       = (['-of', 'COG', '-co', 'BIGTIFF=IF_SAFER', '-co', 'BLOCKSIZE=256', ...],)
self       = <osgeo.gdal.GDALWarpAppOptions;  >

../../.tox/test-rgd-imagery/lib/python3.8/site-packages/osgeo/gdal.py:4667: TypeError
```

I can reproduce this locally on other branches. Something must have changed upstream and we can address in a separate issue/PR. I don't think this is a `large_image` issue but actually a GDAL issue or some other . However, why is it appearing now? We've had plenty of other builds in the last 2 days (last update to large_image_wheels).

**Comment by mcovalt** [comment]
> However, why is it appearing now? We've had plenty of other builds in the last 2 days (last update to large_image_wheels).

It could be related to an update of the system packages of the images? I can investigate, but I'll do that in another branch.

**Comment by mcovalt** [comment]
Created #526 to track the GDAL error.

**Comment by banesullivan** [comment]
Thanks, @mcovalt! Merging...

**Pull request merged**
