### PR TITLE
Upgrade to Django 4

### PR DESCRIPTION
**Pull request by mcovalt**
Upgrades to Django 4 and tests with both Django 3.2+ and Django 4.

### CODE REVIEW

**Comment by mcovalt** [comment]
Tracking https://github.com/jazzband/django-oauth-toolkit/issues/1037 for the remaining issue.

**Comment by banesullivan** [comment]
Is this still blocked? What will it take to pick this up?

**Comment by mcovalt** [comment]
Not blocked anymore. It should be good to go if the tests pass.

**Comment by banesullivan** [comment]
The migrations check is failing for Django 4 😕

**Comment by mcovalt** [comment]
@mvandenburgh Thanks for the heads up! Our requirements are unbound for that package so I think the most recent would be used.

@banesullivan It fails without debug information, unfortunately, too :(

**Pull request merged**
